### ISSUE TITLE
Method id does not accept capital letters and dash

### ISSUE THREAD

**Issue by mzammouri** [owebia/module-shipping-core#2]
The pattern ** ^[a-z][a-z0-9_]*$** used in https://github.com/owebia/module-shipping-core/blob/master/Helper/Config.php#L109 does not allow capital letters and dash for method id, However, on the documentation page, it is stated that the method id accepts **a-z, A-Z, 0-9, - and _**

**Comment by owebia** [comment]
Hi @mzammouri ,
The documentation has some rests of the documentation of the extension for Magento 1.x.

As the id can be used as PHP array key, as javascript array key or as HTML id (and perhaps other languages with extensions), I think it is better to restrict the usage of characters and cases.

I suggest to correct the documentation instead of changing the pattern.

What do you think about it ?
